version: '3'

services:
  
  broker:
    build:
      context: ./../broker
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1