version: '3'

services:

  broker:
    build:
      context: ./../broker
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  auth:
    build:
      context: ./../auth
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"
    depends_on:
      - postgres

  logger:
    build:
      context: ./../logger
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8082:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mongo

  mailer:
    build:
      context: ./../mailer
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8083:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_PORT: 1025
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      MAIL_FROM_ADDRESS: johndoe@example.com
      MAIL_FROM_NAME: John Doe
    depends_on:
      - mailhog
    
  listener:
    build:
      context: ./../listener
      dockerfile: Dockerfile.dev
    restart: on-failure:10
    ports:
      - "8084:80"
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - rabbitmq


  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MONGO_INITDB_DATABASE: logger
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'

  rabbitmq:
    image: 'rabbitmq:3.10.5-management-alpine'
    ports:
      - "5672:5672"
      - "15672:15672" #admin interface
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq